### ISSUE TITLE
Parser panics on out-of-range dates

### ISSUE THREAD

**Issue by killercup** [matthiasbeyer/kairos#13]
(Let me start with: I'm sorry. Fuzzing things is a bit of a hobby of mine. I just opened #12 to add a simple fuzzer for the parse in this library and it turns out it quickly catches an unexpected panic.)

Parsing the string "444411310131440w44444444" panics with "invalid or out-of-range date". You can easily reproduce this with `cargo run --release --example main -- 444411310131440w44444444`.

<details>
<summary>Backtrace (excerpt)</summary>

```
   9:        0x10a9ad918 - core::option::expect_failed::h0ddfb89114e62b70
  10:        0x10a96c062 - chrono::naive::date::NaiveDate::from_ymd::h098a50999e20afc4
  11:        0x10a95f0a5 - <kairos::parser::timetype::ExactDate as core::convert::Into<kairos::timetype::TimeType>>::into::hb9d8b8578059f86b
  12:        0x10a95f4f0 - <kairos::parser::timetype::Date as core::convert::Into<kairos::timetype::TimeType>>::into::hdc9dc20cb554e136
  13:        0x10a961a4b - kairos::parser::parse::hefb263da96e634ec
  14:        0x10a949a75 - main::main::h3c0491c357dfe6d2
```

</details>

- - -

The problem is this: Chrono's `from_ymd`, `from_yo`, etc. methods can all panic.

The solution is this: Use the `_opt` (like `from_ymd_opt`) methods instead, they return an `Option`.

Sadly this means you need to change this `Into<TimeType>`:

https://github.com/matthiasbeyer/kairos/blob/dcc3afaa6299c68988f6daa6b2d4b44920281dd3/src/parser/timetype.rs#L153-L154

**Comment by matthiasbeyer** [comment]
I love it!

**Comment by killercup** [comment]
FYI, changing all these calls to something like

```rust
NaiveDate::from_ymd_opt(year, month, day)
    .and_then(|x| x.and_hms_opt(hour, minute, second))
    .unwrap_or_else(|| ::chrono::Local::now().naive_local());
```

makes cargo fuzz quite happily run 10 million times (I stopped it after a minute) with zero failures and a coverage of 2397 code paths :)

**Comment by matthiasbeyer** [comment]
Uh, this sounds awesome. I will rework this and refactor my code to catch this error, thank you very much for this!

**Comment by killercup** [comment]
You're welcome! I hope you don't need to rewrite your API too much.

Oh, and let me ping https://github.com/rust-lang/rust/issues/33417 from here, because I'd really really really like to have TryInto stabilized!

**Comment by matthiasbeyer** [comment]
Yeah, I basically have to rewrite the internals to be able to return a Result type. But as the public interface already returns a Result the type signature of the `parse` function won't change, I guess.

**Comment by matthiasbeyer** [comment]
I need a bit of your help, if you're willing to:

I created [this patch](https://github.com/matthiasbeyer/kairos/commit/6473d7e095ba8846dbc8e18277b5994487ed4e8e) (feel free to cherry-pick onto your PR, it was created based on [your PR](https://github.com/matthiasbeyer/kairos/pull/12) so it should work) and re-run the fuzzing with `cargo fuzz run parse --release -- -runs=10000000`.

I got this output:

```
INFO: Seed: 757685627
INFO: Loaded 0 modules (0 guards): 
Loading corpus dir: /home/m/archive/development/rust/kairos/fuzz/corpus/parse
INFO: -max_len is not provided, using 64
#0	READ units: 113
#113	INITED cov: 2144 corp: 92/1849b exec/s: 0 rss: 24Mb
#428	NEW    cov: 2151 corp: 93/1857b exec/s: 0 rss: 24Mb L: 8 MS: 5 EraseBytes-ShuffleBytes-ChangeASCIIInt-CrossOver-CrossOver-
#7644	NEW    cov: 2191 corp: 94/1872b exec/s: 0 rss: 24Mb L: 15 MS: 1 EraseBytes-
thread '<unnamed>' panicked at 'invalid or out-of-range date', /checkout/src/libcore/option.rs:874:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
==14271== ERROR: libFuzzer: deadly signal
    #0 0x564f4a6edbb3  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x211bb3)
    #1 0x564f4a71e366  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x242366)
    #2 0x7f317dc3cdaf  (/nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libpthread.so.0+0x11daf)
    #3 0x7f317d68f273  (/nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libc.so.6+0x34273)
    #4 0x7f317d690674  (/nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libc.so.6+0x35674)
    #5 0x564f4a77d678  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x2a1678)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 2 ChangeASCIIInt-CMP- DE: "days"-; base unit: f63da72bae6e8e3248a02e32e9f3c9f07e7e2f0e
0x38,0x38,0x31,0x35,0x31,0x30,0x31,0x2b,0x31,0x32,0x35,0x39,0x31,0x31,0x32,0x35,0x31,0x30,0x30,0x31,0x34,0x31,0x30,0x31,0x6d,0x69,0x6e,0x73,0x65,0x76,0x65,0x72,0x79,0x30,0x33,0x64,0x61,0x79,0x73,0x0,0x0,0x0,0x0,0x0,0x23,0x28,0x32,0x35,0x39,0x44,0x44,0x33,0xa,0xa,0xa,0x68,0x73,0x44,0x31,0x34,0x31,0xe,0x68,0x6f,
8815101+1259112510014101minsevery03days\x00\x00\x00\x00\x00#(259DD3\x0a\x0a\x0ahsD141\x0eho
artifact_prefix='/home/m/archive/development/rust/kairos/fuzz/artifacts/parse/'; Test unit written to /home/m/archive/development/rust/kairos/fuzz/artifacts/parse/crash-1cc71e8fca54b336092953902c34179ad3907f92
Base64: ODgxNTEwMSsxMjU5MTEyNTEwMDE0MTAxbWluc2V2ZXJ5MDNkYXlzAAAAAAAjKDI1OUREMwoKCmhzRDE0MQ5obw==

```

But I fail to understand what's going on here - can you interpret the output for me?

**Comment by killercup** [comment]
Sure! So, first if all, `thread '<unnamed>' panicked at 'invalid or
out-of-range date'` tells you this still fails, and below it is a stack
trace (use `RUST_BACKTRACE=full` for more info).

At the bottom of the output, you can find a reference to
`/home/m/archive/development/rust/kairos/fuzz/artifacts/parse/crash-1cc71e8fca54b336092953902c34179ad3907f92`,
the file which contains the input that produced the crash, as well as the
base64 encoded version of that file.

You can use the input and write a test that runs the parser with that input
to debug this without running the fuzzer.

By the way, if you are using VSCode, I can recommend the LLDB extension,
which allows you to debug rust binaries with break points and inspecting
the stack variables and all that goodness. You'll need to configure it to
run a binary (something like `target/debug/example/foo`), so it's easiest
to write a small example with hardcoded input.

I'll have a look at the actual patch once I'm home.

Matthias Beyer <notifications@github.com> schrieb am Mo. 20. Nov. 2017 um
18:43:

**Comment by matthiasbeyer** [comment]
Funny thing: I am currently trying to reproduce my crash from above (running on 8 cores with 10,000,000 runs max) ... but I cannot reproduce it...

**Comment by matthiasbeyer** [comment]
Nothing said:

```
[7] thread '<unnamed>' panicked at 'invalid or out-of-range date', /checkout/src/libcore/option.rs:874:4
[7] stack backtrace:
[7]    0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
[7]    1: std::sys_common::backtrace::_print
[7]    2: std::panicking::default_hook::{{closure}}
[7]    3: std::panicking::default_hook
[7]    4: std::panicking::rust_panic_with_hook
[7]    5: std::panicking::begin_panic
[7]    6: std::panicking::begin_panic_fmt
[7]    7: rust_begin_unwind
[7]    8: core::panicking::panic_fmt
[7]    9: core::option::expect_failed
[7]   10: <unknown>
[7] ==20872== ERROR: libFuzzer: deadly signal
[7]     #0 0x56338f336d23  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x20bd23)
[7]     #1 0x56338f3674d6  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x23c4d6)
[7]     #2 0x7faf1ed24daf  (/nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libpthread.so.0+0x11daf)
[7]     #3 0x7faf1e777273  (/nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libc.so.6+0x34273)
[7]     #4 0x7faf1e778674  (/nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libc.so.6+0x35674)
[7]     #5 0x56338f3bf558  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x294558)
[7] 
[7] NOTE: libFuzzer has rudimentary signal handlers.
[7]       Combine libFuzzer with AddressSanitizer or similar for better crash reports.
[7] SUMMARY: libFuzzer: deadly signal
[7] MS: 2 EraseBytes-CMP- DE: "yrs"-; base unit: f63da72bae6e8e3248a02e32e9f3c9f07e7e2f0e
[7] 0x38,0x38,0x31,0x35,0x31,0x30,0x30,0x2b,0x31,0x32,0x35,0x39,0x31,0x31,0x32,0x35,0x31,0x30,0x30,0x31,0x34,0x31,0x30,0x31,0x6d,0x69,0x6e,0x73,0x65,0x76,0x65,0x72,0x79,0x30,0x33,0x79,0x72,0x73,0x44,0xa,0xa,0x68,0x73,0x44,0x31,0x34,0x31,0xe,0x68,0x6f,
[7] 8815100+1259112510014101minsevery03yrsD\x0a\x0ahsD141\x0eho
[7] artifact_prefix='/home/m/archive/development/rust/kairos/fuzz/artifacts/parse/'; Test unit written to /home/m/archive/development/rust/kairos/fuzz/artifacts/parse/crash-7f68eaa27e17a1185b6b6802c141431902b80990
[7] Base64: ODgxNTEwMCsxMjU5MTEyNTEwMDE0MTAxbWluc2V2ZXJ5MDN5cnNECgpoc0QxNDEOaG8=
[7] 
[7] =================================================================
[7] ==20872==ERROR: LeakSanitizer: detected memory leaks
[7] 
[7] Direct leak of 120 byte(s) in 1 object(s) allocated from:
[7]     #0 0x56338f32abb6  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x1ffbb6)
[7]     #1 0x56338f3b8a60  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28da60)
[7]     #2 0x56338f3baf5c  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28ff5c)
[7]     #3 0x56338f3bde10  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x292e10)
[7]     #4 0x56338f3bdfe8  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x292fe8)
[7]     #5 0x56338f3b84b2  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28d4b2)
[7]     #6 0x56338f3b86fa  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28d6fa)
[7]     #7 0x7faf1e86b133  (/nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libc.so.6+0x128133)
[7] 
[7] Direct leak of 120 byte(s) in 1 object(s) allocated from:
[7]     #0 0x56338f32abb6  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x1ffbb6)
[7]     #1 0x56338f392b81  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x267b81)
[7] 
[7] Indirect leak of 304 byte(s) in 6 object(s) allocated from:
[7]     #0 0x56338f32abb6  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x1ffbb6)
[7]     #1 0x56338f392b81  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x267b81)
[7] 
[7] Indirect leak of 160 byte(s) in 1 object(s) allocated from:
[7]     #0 0x56338f32abb6  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x1ffbb6)
[7]     #1 0x56338f3b8a60  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28da60)
[7]     #2 0x56338f3ba369  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28f369)
[7]     #3 0x56338f3baf22  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28ff22)
[7]     #4 0x56338f3bde10  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x292e10)
[7]     #5 0x56338f3bdfe8  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x292fe8)
[7]     #6 0x56338f3b84b2  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28d4b2)
[7]     #7 0x56338f3b86fa  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28d6fa)
[7]     #8 0x7faf1e86b133  (/nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libc.so.6+0x128133)
[7] 
[7] Indirect leak of 144 byte(s) in 5 object(s) allocated from:
[7]     #0 0x56338f32abb6  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x1ffbb6)
[7]     #1 0x56338f3b8a60  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28da60)
[7]     #2 0x56338f3ba50b  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28f50b)
[7]     #3 0x56338f3baf22  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28ff22)
[7]     #4 0x56338f3bde10  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x292e10)
[7]     #5 0x56338f3bdfe8  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x292fe8)
[7]     #6 0x56338f3b84b2  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28d4b2)
[7]     #7 0x56338f3b86fa  (/home/m/archive/development/rust/kairos/fuzz/target/x86_64-unknown-linux-gnu/release/parse+0x28d6fa)
[7]     #8 0x7faf1e86b133  (/nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libc.so.6+0x128133)
[7] 
[7] SUMMARY: AddressSanitizer: 848 byte(s) leaked in 14 allocation(s).
[7] MS: 2 EraseBytes-CMP- DE: "yrs"-; base unit: f63da72bae6e8e3248a02e32e9f3c9f07e7e2f0e
[7] 0x38,0x38,0x31,0x35,0x31,0x30,0x30,0x2b,0x31,0x32,0x35,0x39,0x31,0x31,0x32,0x35,0x31,0x30,0x30,0x31,0x34,0x31,0x30,0x31,0x6d,0x69,0x6e,0x73,0x65,0x76,0x65,0x72,0x79,0x30,0x33,0x79,0x72,0x73,0x44,0xa,0xa,0x68,0x73,0x44,0x31,0x34,0x31,0xe,0x68,0x6f,
[7] 8815100+1259112510014101minsevery03yrsD\x0a\x0ahsD141\x0eho
[7] artifact_prefix='/home/m/archive/development/rust/kairos/fuzz/artifacts/parse/'; Test unit written to /home/m/archive/development/rust/kairos/fuzz/artifacts/parse/crash-7f68eaa27e17a1185b6b6802c141431902b80990
[7] Base64: ODgxNTEwMCsxMjU5MTEyNTEwMDE0MTAxbWluc2V2ZXJ5MDN5cnNECgpoc0QxNDEOaG8=
Worker 7 finished fuzzing
```

The file `/home/m/archive/development/rust/kairos/fuzz/artifacts/parse/crash-7f68eaa27e17a1185b6b6802c141431902b80990` contains:

```
8815100+1259112510014101minsevery03yrsD

hsD141^Nho
```

**Comment by killercup** [comment]
Did you figure out what the problem was? I love how the fuzzer is able to generate weird-but-valid looking inputs!

Just ran the fuzzer on your fix-panic branch, and so far I have 81,502,229 runs without errors. I'll leave it running for a bit but probably won't have time to look into it this week.

**Comment by killercup** [comment]
oh, and to reproduce crashes: make sure the input is in the corpus dir. I also tend to add them as tests. you can use rcat (cargo install rcat) to print a binary input in a rust-escaped format (like `b"foo"`).

**Comment by killercup** [comment]
Ah, laptop went silent all of a sudden. It crashed with `b"8815100+1259112510014101minsevery03yrsD\n\nhsD141^Nho\n"` as input, and this stacktrace:

```
#14 0x10517171f in chrono::naive::date::NaiveDate::from_ymd::hbb3fc361bcb2b371 (parse:x86_64+0x1000bd71f)
    #15 0x1050f8695 in kairos::timetype::add_to_moment::h55fdb30553335869 (parse:x86_64+0x100044695)
    #16 0x1050dd74a in kairos::timetype::add::hf7b29de2008faa6c (parse:x86_64+0x10002974a)
    #17 0x1050e12b3 in kairos::timetype::add::_$u7b$$u7b$closure$u7d$$u7d$::ha97905b876b12217 (parse:x86_64+0x10002d2b3)
```

so somwhere in this fn

https://github.com/matthiasbeyer/kairos/blob/fix-panic/src/timetype.rs#L778

which does not use the _opt methods.

**Comment by matthiasbeyer** [comment]
Pushed a fix for your latest report, thank you very much! Apparently, there where several points where I had to move from `NaiveDate::from_ymd` to `NaiveDate::from_ymd_opt` (and friends).

All remaining usages of `from_ymd()` should be in the tests now...

**Comment by killercup** [comment]
Cool! Just pulled and started fuzzing again. It seems to be really slow now. Maybe it's my setup, but this one just took 35 seconds:

`b"8815100+1259112510014101minsevery03yrsD\n\nhsD141^Nho\n"`

Also I'm getting ~30 exec/s where before it was more like 50k!

**Comment by matthiasbeyer** [comment]
I'm not sure how to use `rcat` on this?

Speed-wise I get up to 60k, if I read that correctly:

```
#58989	NEW    cov: 3595 corp: 150/3253b exec/s: 58989 rss: 66Mb L: 64 MS: 1 CrossOver-
#60425	NEW    cov: 3630 corp: 151/3317b exec/s: 60425 rss: 68Mb L: 64 MS: 2 ChangeASCIIInt-CMP- DE: "hourly"-
#68129	NEW    cov: 3643 corp: 152/3380b exec/s: 68129 rss: 73Mb L: 63 MS: 1 EraseBytes-
#73151	NEW    cov: 3660 corp: 153/3444b exec/s: 36575 rss: 77Mb L: 64 MS: 3 ChangeBit-ChangeASCIIInt-CMP- DE: "monthly"-
#84464	NEW    cov: 3665 corp: 154/3505b exec/s: 42232 rss: 85Mb L: 61 MS: 1 EraseBytes-
#90884	NEW    cov: 3668 corp: 155/3561b exec/s: 45442 rss: 90Mb L: 56 MS: 1 EraseBytes-
```

**Comment by killercup** [comment]
like this:

> rcat --quote fuzz/artifacts/parse/slow-unit-02de8b0d465acb898a741702108c4a1183ffbd05

maybe the speed is a problem with my machine, i'll cargo clean and remove the corpus later to test this

**Comment by matthiasbeyer** [comment]
Hm, with `cargo fuzz run parse --release -- -max_total_time=$(( 60 * 3 ))` I just got `Done 21474 runs in 243 second(s)`, which is really few. But like two minutes before I got 60k... nothing changed in the source. Maybe that's an instability with rustc nightly?

**Comment by matthiasbeyer** [comment]
Any more comments? I think about merging #15 which would end up beeing `beta-2` then... If there are no more crashes I'd go ahead and release `0.1.0` after the `beta-2` release,... speed is (IMO) not _that_ much of a problem... at least we are pre-1.0, so I guess that's okay...

**Comment by killercup** [comment]
LGTM.

…but did you see Rust stable now has ? for Option? :D

**Comment by matthiasbeyer** [comment]
Nice! But I want to be able to support some older versions of the compiler, so I won't use it for another 2 months or so before we switch the minimum required compiler version up (also in my other projects)! Thanks for mentioning, though!
